on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    name: Build Resume
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install dependencies
        run: npm install

      - name: Build resume
        run: npm run build

      - name: Upload artifacts
        # Upload the resume.pdf file as an artifact only on main branch
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v2
        with:
          path: out/resume.pdf

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            out/resume.pdf
